# Chinese translations for PROJECT.
# Copyright (C) 2024 ORGANIZATION
# This file is distributed under the same license as the PROJECT project.
# FIRST AUTHOR <EMAIL@ADDRESS>, 2024.
#
msgid ""
msgstr ""
"Project-Id-Version: PROJECT VERSION\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2024-08-06 21:17+0800\n"
"PO-Revision-Date: 2024-08-06 21:17+0800\n"
"Last-Translator: \n"
"Language: zh\n"
"Language-Team: zh <LL@li.org>\n"
"Plural-Forms: nplurals=1; plural=0;\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.15.0\n"

#: kvmd/htclient.py:63
msgid "Can't determine filename"
msgstr "无法确定文件名"

#: kvmd/inotify.py:199
#, python-format
msgid "Watching for %s"
msgstr "监视 %s"

#: kvmd/inotify.py:258
#, python-format
msgid "Unwatching %s because IGNORED was received"
msgstr "因收到忽略标识而取消监视 %s"

#: kvmd/usb.py:36
msgid "Can't find any UDC"
msgstr "未找到任何 UDC"

#: kvmd/apps/__init__.py:132
msgid "Set config file path"
msgstr "设置配置文件路径"

#: kvmd/apps/__init__.py:134
msgid "Override config options list (like sec/sub/opt=value)"
msgstr "覆盖配置文件选项列表（如 sec/sub/opt=value）"

#: kvmd/apps/__init__.py:136
msgid "View current configuration (include all overrides)"
msgstr "查看当前配置（包括所有覆盖配置文件）"

#: kvmd/apps/__init__.py:139
msgid "Run the service"
msgstr "启动此服务"

#: kvmd/apps/__init__.py:165
msgid ""
"To prevent accidental startup, you must specify the --run option to "
"start.\n"
msgstr "为了防止意外启动，必须在启动时指定 --run 选项。\n"

#: kvmd/apps/__init__.py:165
msgid "Try the --help option to find out what this service does.\n"
msgstr "尝试使用 --help 选项来了解某项服务的功能。\n"

#: kvmd/apps/__init__.py:165
msgid "Make sure you understand exactly what you are doing!"
msgstr "请确定你自己在做什么！"

#: kvmd/apps/kvmd/auth.py:57
msgid "AUTHORIZATION IS DISABLED"
msgstr "身份验证服务已被禁用"

#: kvmd/apps/kvmd/auth.py:61
#, python-format
msgid "Authorization is disabled for API %r"
msgstr "由于 API %r 身份验证服务已被禁用"

#: kvmd/apps/kvmd/auth.py:66
#, python-format
msgid "Using internal auth service %r"
msgstr "使用内部身份验证服务 %r"

#: kvmd/apps/kvmd/auth.py:73
#, python-format
msgid "Using external auth service %r"
msgstr "使用外部身份验证服务 %r"

#: kvmd/apps/kvmd/auth.py:101
#, python-format
msgid "Got access denied for user %r by TOTP"
msgstr "用户 %r 被 TOTP 拒绝访问"

#: kvmd/apps/kvmd/auth.py:112
#, python-format
msgid "Authorized user %r via auth service %r"
msgstr "用户 %r 已通过身份认证服务 %r 授权"

#: kvmd/apps/kvmd/auth.py:114
#, python-format
msgid "Got access denied for user %r from auth service %r"
msgstr "身份验证服务 %r 拒绝了用户 %r 的访问请求"

#: kvmd/apps/kvmd/auth.py:124
#, python-format
msgid "Logged in user %r"
msgstr "已登录用户 %r"

#: kvmd/apps/kvmd/auth.py:134
msgid "Can't generate new unique token"
msgstr "无法生成新的唯一令牌"

#: kvmd/apps/kvmd/auth.py:145
#, python-format
msgid "Logged out user %r (%d)"
msgstr "已注销用户 %r (%d)"

#: kvmd/plugins/atx/__init__.py:45
msgid "Performing another ATX operation, please try again later"
msgstr "正在处理另一个  ATX 动作，请稍等"

#: kvmd/plugins/atx/gpio.py:209
#, python-format
msgid "Clicked ATX button %r"
msgstr "ATX 按钮 %r 被点击"

#: kvmd/plugins/auth/http.py:94
#, python-format
msgid "Failed HTTP auth request for user %r"
msgstr "用户 %r 的 HTTP 验证请求失败"

#: kvmd/plugins/auth/ldap.py:106
#, python-format
msgid "LDAP server is down: %s"
msgstr "LDAP 服务已下线： %s"

#: kvmd/plugins/auth/ldap.py:108
#, python-format
msgid "Unexpected LDAP error: %s"
msgstr "LDAP 未知错误： %s"

#: kvmd/plugins/auth/pam.py:91
#, python-format
msgid "Unallowed UID of user %r: uid=%d < allow_uids_at=%d"
msgstr "未授权 UID user %r: uid=%d < allow_uids_at=%d"

#: kvmd/plugins/auth/pam.py:97
#, python-format
msgid "Can't authorize user %r using PAM: code=%d; reason=%s"
msgstr "无法使用 PAM 验证用户  %r ：code=%d；reason=%s"

#: kvmd/plugins/auth/radius.py:445
#, python-format
msgid "Failed RADIUS auth request for user %r"
msgstr "用户 %r 的 RADIUS 验证请求失败"

#: kvmd/plugins/hid/bt/__init__.py:137 kvmd/plugins/hid/ch9329/__init__.py:99
msgid "Starting HID daemon ..."
msgstr "正在启动 HID 守护程序......"

#: kvmd/plugins/hid/bt/__init__.py:182 kvmd/plugins/hid/ch9329/__init__.py:141
msgid "Stopping HID daemon ..."
msgstr "正在启停止 HID 守护程序......"

#: kvmd/plugins/hid/bt/__init__.py:231
msgid "Unexpected HID error"
msgstr "未知 HID 错误"

#: kvmd/plugins/hid/bt/server.py:153
#, python-format
msgid "Listening [%s]:%d for %s ..."
msgstr "监听 [%s]:%d for %s ..."

#: kvmd/plugins/hid/bt/server.py:190
#, python-format
msgid "CTL socket error on %s: %s"
msgstr "CTL 套接字错误 ： %s: %s"

#: kvmd/plugins/hid/bt/server.py:204
#, python-format
msgid "INT socket error on %s: %s"
msgstr "INT 套接字错误 ： %s: %s"

#: kvmd/plugins/hid/bt/server.py:287
#, python-format
msgid "Can't send %s report to %s: %s"
msgstr "无法向 %s 发送 %s 报告： %s"

#: kvmd/plugins/hid/bt/server.py:314
#, python-format
msgid "Can't accept %s client"
msgstr "无法接受 %s 客户端"

#: kvmd/plugins/hid/bt/server.py:319
#, python-format
msgid "Refused %s client: %s: max clients reached"
msgstr "拒绝 %s 客户端：%s：已到达最大客户端数量"

#: kvmd/plugins/hid/bt/server.py:328
#, python-format
msgid "Accepted %s client: %s"
msgstr "已接受 %s 客户端： %s"

#: kvmd/plugins/hid/bt/server.py:340
#, python-format
msgid "Closed %s client %s"
msgstr "关闭 %s 客户端 %s"

#: kvmd/plugins/hid/bt/server.py:375
msgid "Publishing ..."
msgstr "广播中......"

#: kvmd/plugins/hid/bt/server.py:375
msgid "Unpublishing ..."
msgstr "取消广播......"

#: kvmd/plugins/hid/bt/server.py:379
#, python-format
msgid "Can't change public mode: %s"
msgstr "无法更改公共模式：%s"

#: kvmd/plugins/hid/bt/server.py:383
#, python-format
msgid "Unpairing %s ..."
msgstr "正在取消配对 %s ......"

#: kvmd/plugins/hid/bt/server.py:387
#, python-format
msgid "Can't unpair %s: %s"
msgstr "无法取消配对 %s: %s"

#: kvmd/plugins/hid/ch9329/__init__.py:178
#, python-format
msgid "HID : mouse output = %s"
msgstr "HID：鼠标输出 = %s"

#: kvmd/plugins/hid/ch9329/__init__.py:208
msgid "Unexpected error in the run loop"
msgstr "运行循环中出现意外错误"

#: kvmd/plugins/hid/ch9329/__init__.py:231
msgid "Unexpected error in the HID loop"
msgstr "HID 循环中出现意外错误"

#: kvmd/plugins/hid/ch9329/chip.py:58
msgid "Too short response, HID might be disconnected"
msgstr "响应时间太短，HID 可能已断开"

#: kvmd/plugins/hid/ch9329/chip.py:64
msgid "Invalid response checksum"
msgstr "响应校验和无效"

#: kvmd/plugins/hid/otg/device.py:125
#, python-format
msgid "Unexpected HID-%s error"
msgstr "HID-%s 意外错误"

#: kvmd/plugins/hid/otg/device.py:152
#, python-format
msgid "Stopping HID-%s daemon ..."
msgstr "清除 HID-%s 鼠标事件 ......"

#: kvmd/plugins/hid/otg/device.py:197
#, python-format
msgid "HID-%s write() error: written (%s) != report length (%d)"
msgstr "HID-%s write() 错误：写入 (%s) != 报告长度 (%d)"

#: kvmd/plugins/hid/otg/device.py:205
#, python-format
msgid "HID-%s busy/unplugged (write): %s"
msgstr "HID-%s 忙碌/已拔（写入）： %s"

#: kvmd/plugins/hid/otg/device.py:207
#, python-format
msgid "Can't write report to HID-%s"
msgstr "无法将内容写入 HID-%s"

#: kvmd/plugins/hid/otg/device.py:224
#, python-format
msgid "Can't select() for read HID-%s: %s"
msgstr "读取 HID-%s 时无法选择 %s"

#: kvmd/plugins/hid/otg/device.py:232
#, python-format
msgid "HID-%s busy/unplugged (read): %s"
msgstr "HID-%s 忙碌/已拔（读取）： %s"

#: kvmd/plugins/hid/otg/device.py:234
#, python-format
msgid "Can't read report from HID-%s"
msgstr "无法读取 HID-%s 的回复"

#: kvmd/plugins/hid/otg/device.py:251
#, python-format
msgid "Missing HID-%s device: %s"
msgstr "丢失 HID-%s 设备：%s"

#: kvmd/plugins/hid/otg/device.py:263
#, python-format
msgid "Can't open HID-%s device %s: %s"
msgstr "无法打开 HID-%s 设备 %s: %s"

#: kvmd/plugins/hid/otg/device.py:274
#, python-format
msgid "HID-%s is busy/unplugged (write select)"
msgstr "HID-%s 忙碌/已拔（写入切换）"

#: kvmd/plugins/hid/otg/device.py:276
#, python-format
msgid "Can't select() for write HID-%s: %s"
msgstr "写 HID-%s 时无法选择 %s"

#: kvmd/plugins/hid/otg/keyboard.py:62
msgid "Clearing HID-keyboard events ..."
msgstr "清除 HID 键盘事件 ......"

#: kvmd/plugins/hid/otg/mouse.py:71
msgid "Clearing HID-mouse events ..."
msgstr "清除 HID 鼠标事件 ......"

#: kvmd/plugins/msd/__init__.py:57
msgid "Performing another MSD operation, please try again later"
msgstr "正在执行另一项虚拟存储驱动器操作，请稍后再试"

#: kvmd/plugins/msd/__init__.py:63
msgid "MSD is not found"
msgstr "虚拟存储驱动器不存在"

#: kvmd/plugins/msd/__init__.py:69
msgid "MSD is connected to Server, but shouldn't for this operation"
msgstr "虚拟存储驱动器已连接到服务器，但本操作不应连接到服务器"

#: kvmd/plugins/msd/__init__.py:75
msgid "MSD is disconnected from Server, but should be for this operation"
msgstr "虚拟存储驱动器与服务器断开连接，但进行此操作时应断开连接"

#: kvmd/plugins/msd/__init__.py:81
msgid "The image is not selected"
msgstr "没有选中任何镜像"

#: kvmd/plugins/msd/__init__.py:87
msgid "The image is not found in the storage"
msgstr "存储区中没有找到镜像"

#: kvmd/plugins/msd/__init__.py:93
msgid "This image is already exists"
msgstr "此镜像已存在"

#: kvmd/plugins/msd/disabled.py:40
msgid "MSD is disabled"
msgstr "虚拟存储驱动器已被禁用"

#: kvmd/plugins/msd/otg/__init__.py:148
#, python-format
msgid "Using OTG gadget %r as MSD"
msgstr "使用 OTG gadget %r 作为 MSD"

#: kvmd/plugins/msd/otg/__init__.py:223
msgid "Can't reset MSD properly"
msgstr "无法正确重置虚拟存储驱动器"

#: kvmd/plugins/msd/otg/__init__.py:442
msgid "Unexpected MSD watcher error"
msgstr "虚拟存储驱动器监视器意外出错"

#: kvmd/plugins/msd/otg/__init__.py:461
msgid "Probing to remount storage ..."
msgstr "探测以重新挂载存储 ......"

#: kvmd/plugins/msd/otg/__init__.py:467
msgid "Error while reloading MSD state; switching to offline"
msgstr "重新加载 MSD 状态时出错；切换到离线状态"

#: kvmd/plugins/msd/otg/__init__.py:495
#, python-format
msgid "Setting up initial image %r ..."
msgstr "设置初始镜像 %r ......"

#: kvmd/plugins/msd/otg/__init__.py:501
msgid "Can't setup initial image: ignored"
msgstr "无法设置初始镜像 %r: 已忽略"

#: kvmd/plugins/msd/otg/__init__.py:503
#, python-format
msgid "Can't find initial image %r: ignored"
msgstr "找不到初始镜像 %r: 已忽略"

#: kvmd/plugins/msd/otg/drive.py:36
msgid "MSD drive is locked on IO operation"
msgstr "虚拟存储驱动器在 IO 操作时被锁定"

#: kvmd/plugins/msd/otg/storage.py:297
msgid "Can't execute remount helper"
msgstr "无法执行重新挂载辅助程序"

#: kvmd/plugins/ugpio/anelpwr.py:152
#, python-format
msgid "Failed ANELPWR POST request to pin %s: %s"
msgstr "向引脚 %s 发送 ANELPWR POST 请求失败：%s"

